version: '2'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/,http://localhost:8762/eureka/
    restart: always
    depends_on:
      - vault
      - registry1
  registry1:
    build: ./registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=registry1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8762/eureka/
    depends_on:
      - vault
  registry2:
    build: ./registry
    ports:
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=registry2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/
    depends_on:
      - vault
  vault:
    image: vault