spring.application.name: gateway

server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry1:8761/eureka/v2/,http://registry2:8762/eureka/v2/

logging:
  level:
    root: WARN
    com.dubyatoo: TRACE
    
zuul:
  routes:
    google:
      path: /google/**
      url: http://www.google.com
   
ribbon:
  eureka.enabled: true