spring.application.name: gateway

server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ec2-54-197-19-241.compute-1.amazonaws.com:8761/eureka/

logging:
  level:
    root: WARN
    com.dubyatoo: TRACE
    
zuul:
  routes:
    google:
      path: /google/**
      url: http://www.google.com
   
ribbon:
  eureka.enabled: true