spring.application.name: gateway

server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://duxtop:8761/eureka/

logging:
  level:
    root: WARN
    com.dubyatoo: TRACE
    
zuul:
  routes:
    google:
      path: /google/**
      url: http://www.google.com
   
ribbon:
  eureka.enabled: true