---
# Spring Boot 1.5.9.RELEASE
# mavenBom org.springframework.cloud:spring-cloud-dependencies:Edgware.RELEASE
# Do not use "/v2/", incompatible with Peer Awareness in 1.5.9/Edgware it seems
spring.application.name: registry

eureka:
  instance:
    preferIpAddress: false
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck.enabled: true
    serviceUrl.defaultZone: http://ec2-54-197-19-241.compute-1.amazonaws.com:8761/eureka/,http://ec2-54-152-148-58.compute-1.amazonaws.com:8762/eureka/,http://ec2-54-172-170-95.compute-1.amazonaws.com:8763/eureka/

  server:
    registrySyncRetries: 1
    enable-self-preservation: false

logging:
  level:
    root: WARN
    com.dubyatoo: TRACE

---
spring.profiles: registry1

server.port: 8761

eureka:
  instance:
    hostname: peer1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  
---
spring.profiles: registry2

server.port: 8762

eureka:
  instance:
    hostname: peer2
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring.profiles: registry3

server.port: 8763

eureka:
  instance:
    hostname: peer3
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}